<?xml version="1.0" encoding="UTF-8"?>
<definitions name="GetFinEventCategoryService" targetNamespace="http://j2ee.netbeans.org/wsdl/WholesaleBookingProcessor-BPEL/src/GetFinEventCategoryService"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://j2ee.netbeans.org/wsdl/WholesaleBookingProcessor-BPEL/src/GetFinEventCategoryService" xmlns:ns="http://eu.squadd/connectors/wholesaleBooking" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
    <types>
        <xsd:schema targetNamespace="http://j2ee.netbeans.org/wsdl/WholesaleBookingProcessor-BPEL/src/GetFinEventCategoryService">
            <xsd:import namespace="http://eu.squadd/connectors/wholesaleBooking" schemaLocation="FinancialEventCategoryDAO.xsd"/>
        </xsd:schema>
    </types>
    <message name="GetFinEventCategoryServiceOperationRequest">
        <part name="productId" type="xsd:integer"/>
        <part name="homeEqualsServiceSbidIndicator" type="xsd:string"/>
        <part name="altBookingIndicator" type="xsd:boolean"/>
        <part name="iecCode" type="xsd:integer"/>
        <part name="debitCreditIndicator" type="xsd:string"/>
    </message>
    <message name="GetFinEventCategoryServiceOperationResponse">
        <part name="finEventCategoryOutput" type="ns:FinancialEventCategoryDAO"/>
    </message>
    <portType name="GetFinEventCategoryServicePortType">
        <operation name="GetFinEventCategoryServiceOperation">
            <input name="input" message="tns:GetFinEventCategoryServiceOperationRequest"/>
            <output name="output" message="tns:GetFinEventCategoryServiceOperationResponse"/>
        </operation>
    </portType>
    <plnk:partnerLinkType name="GetFinEventCategoryService">
        <!-- A partner link type is automatically generated when a new port type is added. Partner link types are used by BPEL processes. 
In a BPEL process, a partner link represents the interaction between the BPEL process and a partner service. Each partner link is associated with a partner link type.
A partner link type characterizes the conversational relationship between two services. The partner link type can have one or two roles.-->
        <plnk:role name="GetFinEventCategoryServicePortTypeRole" portType="tns:GetFinEventCategoryServicePortType"/>
    </plnk:partnerLinkType>
</definitions>
